language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install pyasn1 asn1crypto libsnmp pyparsing pysnmp
script:
  - coverage run --source=asn1tools setup.py test
  - env PYTHONPATH=. python examples/benchmarks/packages.py
  - env PYTHONPATH=. python examples/benchmarks/codecs.py
  - env PYTHONPATH=. python examples/question.py
after_success:
  coveralls
